package com.android.id.peers.members.models

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
class MemberAcquisitionConfig (
    var jenisIdentitas: Int = 1,
    var noIdentitas: Int = 1,
    var namaLengkap: Int = 1,
//    var memberHandphone: Int = 1,
    var tanggalLahir: Int = 1,
    var tempatLahir: Int = 1,
    var jenisKelamin: Int = 1,
    var namaGadisIbu: Int = 1,
    var statusPerkawinan: Int = 1,
    var pendidikanTerakhir: Int = 1,
    var alamatKtpJalan: Int = 1,
    var alamatKtpNo: Int = 1,
    var alamatKtpRt: Int = 1,
    var alamatKtpRw: Int = 1,
    var alamatKtpKelurahan: Int = 1,
    var alamatKtpKecamatan: Int = 1,
    var alamatKtpKota: Int = 1,
    var alamatKtpProvinsi: Int = 1,
    var alamatKtpStatusTempatTinggal: Int = 1,
    var alamatKtpLamaTinggal: Int = 1,
    var domisiliSesuaiKtp: Int = 1,
    var alamatDomisiliJalan: Int = 1,
    var alamatDomisiliNo: Int = 1,
    var alamatDomisiliRt: Int = 1,
    var alamatDomisiliRw: Int = 1,
    var alamatDomisiliKelurahan: Int = 1,
    var alamatDomisiliKecamatan: Int = 1,
//    var alamatDomisiliKotaProvinsi: Int = 1,
    var alamatDomisiliKota: Int = 1,
    var alamatDomisiliProvinsi: Int = 1,
    var alamatDomisiliStatusTempatTinggal: Int = 1,
    var alamatDomisiliLamaTempatTinggal: Int = 1,
    var memilikiNpwp: Int = 1,
    var nomerNpwp: Int = 1,
    var pekerjaUsaha: Int = 1,
    var bidangPekerja: Int = 1,
    var posisiJabatan: Int = 1,
    var namaPerusahaan: Int = 1,
    var lamaBekerja: Int = 1,
    var penghasilanOmset: Int = 1,
    var alamatKantorJalan: Int = 1,
    var alamatKantorNo: Int = 1,
    var alamatKantorRt: Int = 1,
    var alamatKantorRw: Int = 1,
    var alamatKantorKelurahan: Int = 1,
    var alamatKantorKecamatan: Int = 1,
//    var alamatKantorKotaProvinsi: Int = 1,
    var alamatKantorKota: Int = 1,
    var alamatKantorProvinsi: Int = 1,
    var namaEmergency: Int = 1,
    var noHpEmergency: Int = 1,
    var hubungan: Int = 1

): Parcelable